In this module, we will cover full structural equation modeling (SEM) and take a deep dive into mediation analysis as a
motivating application of SEM.

<a href = "/lavaan-e-learning/4_sem_mediation/sem_mediation.pdf" class = "button button1">Lecture Slides</a>

## Videos

### Full SEM

{{< video https://youtu.be/bbRZOGLvZA0 >}}

### Mediation Basics

{{< video https://youtu.be/XSa7ZLvomCg >}}

### Mediation Testing

{{< video https://youtu.be/du0t_brdB2A >}}

### Bootstrapping

{{< video https://youtu.be/iIeanANyKd8 >}}

### Parallel Multiple Mediator Models

**Note:** In the following recording, I misspoke when discussing the bias-corrected and accelerated confidence interval
(BCa CI) on Slide 75. While the BCa CI does, indeed, correct for bias and skewness in the empirical sampling distribution,
the CI calculated by lavaan::parameterEstimates() when specifying boot.ci.type = "bca.simple" does not include the
acceleration correction. So, the intervals we get from lavaan are only corrected for bias in the empirical sampling
distribution. For more (technical) information about the different flavors of bootstrapped CI, see
[DiCiccio & Efron (1996)](https://doi.org/10.1214/ss/1032280214).

{{< video https://youtu.be/NVlcF6fiOI4 >}}

### Serial Multiple Mediator Models

{{< video https://youtu.be/inPb6ev6APQ >}}

### Model Modification & Pruning

{{< video https://youtu.be/GvJvGCRGgBI >}}

### Bigger Models

{{< video https://youtu.be/mRJ8LxoJzOw >}}

### Mediation with Latent Variables

{{< video https://youtu.be/_7LnAs_p-PU >}}
